### ISSUE TITLE
Collect initial "Vision and Goals" for wiki

### ISSUE THREAD

**Issue by gkrueger89** [infrains/concept#1]
In the first mail communications we were thinking about the vision and goals for **Infrains**.

We should track that in the wiki in order to stay up-to-date with our vision and to use a central shared space.

**Comment by gkrueger89** [comment]
Inserted the vision and mission thoughts from mail conversation to wiki page. Please review @jfknauf

**Comment by jfknauf** [comment]
Fixed some typos. Otherwise looks good. Regarding as done.
